spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
server:
  port: 8081
jwt:
  secret: ${JWT_SECRET}
  access_lifetime: ${JWT_ACCESS_TIME}
  refresh_lifetime: ${JWT_REFRESH_TIME}
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
server:
  port: 8081
jwt:
  secret: ${JWT_SECRET}
  access_lifetime: ${JWT_ACCESS_TIME}
  refresh_lifetime: ${JWT_REFRESH_TIME}


