name: authentication_service_pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build-test-sonar-docker:
    name: Build, Test, Sonar, Docker
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER_IMAGE_NAME: authentication_service
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package -DskipTests -B
        working-directory: authenticationservice

      - name: Copy Maven dependencies
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency -B
        working-directory: authenticationservice

      - name: Run Tests
        run: mvn test jacoco:report -B
        working-directory: authenticationservice

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=rommarddinio_java_advanced_innowise
            -Dsonar.organization=rommarddinio
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=authenticationservice/src/main/java,authenticationservice/target/generated-sources/annotations
            -Dsonar.tests=authenticationservice/src/test/java
            -Dsonar.java.binaries=authenticationservice/target/classes
            -Dsonar.java.libraries=authenticationservice/target/dependency/**/*.jar
            -Dsonar.java.test.binaries=authenticationservice/target/test-classes
            -Dsonar.java.test.libraries=authenticationservice/target/dependency/**/*.jar
            -Dsonar.coverage.jacoco.xmlReportPaths=authenticationservice/target/site/jacoco/jacoco.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest .
        working-directory: authenticationservice

      - name: Push Docker image
        run: docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
        working-directory: authenticationservice