name: sonar

on:
  push:
    branches:
      - '**'

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Run Tests and Generate Jacoco Reports for Order Service
        run: mvn clean test jacoco:report -B
        working-directory: orderservice

      - name: Run Tests and Generate Jacoco Reports for Authentication Service
        run: mvn clean test jacoco:report -B
        working-directory: authenticationservice

      - name: Run Tests and Generate Jacoco Reports for User Service
        run: mvn clean test jacoco:report -B
        working-directory: userservice

      - name: Copy dependencies for Order Service
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency -B
        working-directory: orderservice

      - name: Copy dependencies for Authentication Service
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency -B
        working-directory: authenticationservice

      - name: Copy dependencies for User Service
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency -B
        working-directory: userservice

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=rommarddinio_java_advanced_innowise
            -Dsonar.organization=rommarddinio
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=authenticationservice/src/main/java,userservice/src/main/java,authenticationservice/target/generated-sources/annotations,userservice/target/generated-sources/annotations,orderservice/src/main/java,orderservice/target/generated-sources/annotations
            -Dsonar.tests=authenticationservice/src/test/java,userservice/src/test/java,orderservice/src/test/java
            -Dsonar.java.binaries=authenticationservice/target/classes,userservice/target/classes,orderservice/target/classes
            -Dsonar.java.libraries=authenticationservice/target/dependency/**/*.jar,userservice/target/dependency/**/*.jar, orderservice/target/dependency/**/*.jar
            -Dsonar.java.test.binaries=authenticationservice/target/test-classes,userservice/target/test-classes,orderservice/target/test-classes
            -Dsonar.java.test.libraries=authenticationservice/target/dependency/**/*.jar,userservice/target/dependency/**/*.jar, orderservice/target/dependency/**/*.jar
            -Dsonar.coverage.jacoco.xmlReportPaths=authenticationservice/target/site/jacoco/jacoco.xml,userservice/target/site/jacoco/jacoco.xml,orderservice/target/site/jacoco/jacoco.xml